"""
Chat and Proactive Queue routes.
Integrates with the Orchestrator for handling chat interactions
and exposes the Proactive Suggestions queue.
"""

from typing import List, Optional
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from pydantic import BaseModel, Field

from app.db.database import get_db
from app.db.models import ProactiveSuggestion
from app.agents.orchestrator import Orchestrator
from app.models.responses import BaseResponse
from app.utils.logger import get_logger

log = get_logger(__name__)

router = APIRouter(prefix="/chat", tags=["Chat & Proactive Queue"])

# --- Request/Response Models ---

class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, description="The user chat message")
    session_id: Optional[str] = Field(None, description="The optional unique session identifier")

class ChatResponse(BaseResponse):
    response: str = Field(..., description="The response generated by the multi-agent system")
    classification: str = Field(..., description="The categorized intent ('scheduling', 'knowledge', 'chat')")
    session_id: str = Field(..., description="The active short-term session ID")

class ProactiveSuggestionItem(BaseModel):
    id: int = Field(..., description="Unique suggestion ID")
    timestamp: datetime = Field(..., description="Creation timestamp")
    suggestion_text: str = Field(..., description="The actual recommendation text")
    triggered_context: Optional[str] = Field(None, description="Context conditions that triggered this suggestion")
    acknowledged: bool = Field(..., description="Whether the user acknowledged this suggestion")
    resolved: bool = Field(..., description="Whether the suggestion was resolved")

    class Config:
        from_attributes = True

class ProactiveQueueResponse(BaseResponse):
    suggestions: List[ProactiveSuggestionItem] = Field(..., description="List of proactive suggestions")

# --- Routes ---

@router.post("", response_model=ChatResponse)
async def chat_interaction(request: ChatRequest, db: Session = Depends(get_db)):
    """
    Main chat gateway. Routes user message through the Multi-Agent Orchestrator
    and returns the specialized agent's response, classification intent, and active session ID.
    """
    log.info(f"API chat: Handling chat request for session '{request.session_id}'")
    try:
        orchestrator = Orchestrator(db_session=db, session_id=request.session_id)
        result = await orchestrator.handle_message(message=request.message)
        
        return ChatResponse(
            success=True,
            response=result["response"],
            classification=result["classification"],
            session_id=result["session_id"]
        )
    except Exception as e:
        log.error(f"API chat: Error during chat interaction: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="An error occurred while processing the chat interaction."
        )

@router.get("/proactive", response_model=ProactiveQueueResponse)
async def get_proactive_queue(db: Session = Depends(get_db)):
    """
    Retrieves the background generated proactive suggestions from the database.
    Sorted by latest timestamp first.
    """
    log.info("API chat: Fetching proactive suggestions queue")
    try:
        suggestions = db.query(ProactiveSuggestion).order_by(ProactiveSuggestion.timestamp.desc()).all()
        return ProactiveQueueResponse(
            success=True,
            suggestions=[ProactiveSuggestionItem.model_validate(s) for s in suggestions]
        )
    except Exception as e:
        log.error(f"API chat: Error retrieving proactive queue: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to retrieve the proactive suggestions queue."
        )

@router.post("/proactive/{suggestion_id}/acknowledge", response_model=BaseResponse)
async def acknowledge_suggestion(suggestion_id: int, db: Session = Depends(get_db)):
    """
    Marks a proactive suggestion as acknowledged.
    """
    log.info(f"API chat: Acknowledging suggestion ID {suggestion_id}")
    suggestion = db.query(ProactiveSuggestion).filter(ProactiveSuggestion.id == suggestion_id).first()
    if not suggestion:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"ProactiveSuggestion with ID {suggestion_id} not found."
        )
    
    try:
        suggestion.acknowledged = True
        db.commit()
        return BaseResponse(success=True)
    except Exception as e:
        db.rollback()
        log.error(f"API chat: Error acknowledging suggestion {suggestion_id}: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to update acknowledgment status."
        )

@router.post("/proactive/{suggestion_id}/resolve", response_model=BaseResponse)
async def resolve_suggestion(suggestion_id: int, db: Session = Depends(get_db)):
    """
    Marks a proactive suggestion as resolved.
    """
    log.info(f"API chat: Resolving suggestion ID {suggestion_id}")
    suggestion = db.query(ProactiveSuggestion).filter(ProactiveSuggestion.id == suggestion_id).first()
    if not suggestion:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"ProactiveSuggestion with ID {suggestion_id} not found."
        )
    
    try:
        suggestion.resolved = True
        db.commit()
        return BaseResponse(success=True)
    except Exception as e:
        db.rollback()
        log.error(f"API chat: Error resolving suggestion {suggestion_id}: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to update resolution status."
        )
